Resources:
  PollyBlogBucket91106725:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: aws-cdk:cr-owned:baee5295
          Value: "true"
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/PollyBlogBucket/Resource
  PollyBlogBucketPolicy9B0AFE09:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: PollyBlogBucket91106725
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - MediaDistributionOrigin1S3Origin173ACFA0
                  - S3CanonicalUserId
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - PollyBlogBucket91106725
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/PollyBlogBucket/Policy/Resource
  DeploySampleVideoAwsCliLayer2C4BD2C0:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68.zip
      Description: /opt/awscli/aws
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/DeploySampleVideo/AwsCliLayer/Resource
      aws:asset:path: /Users/akodali/pollyblog/polly-blog-cdk/node_modules/aws-cdk-lib/lambda-layer-awscli/lib/layer.zip
      aws:asset:is-bundled: false
      aws:asset:property: Content
  DeploySampleVideoCustomResource5951910B:
    Type: Custom::CDKBucketDeployment
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536
          - Arn
      SourceBucketNames:
        - Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
      SourceObjectKeys:
        - aac0c61b8ac23e2a99368810fc2b45a8170c9ea718c5e4d5fb6e49413461bace.zip
      DestinationBucketName:
        Ref: PollyBlogBucket91106725
      Prune: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/DeploySampleVideo/CustomResource/Default
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
                    - /*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - PollyBlogBucket91106725
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - PollyBlogBucket91106725
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      Roles:
        - Ref: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/DefaultPolicy/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: e3d9996b6fafcc7da88312672e15e3cc925b02cffc6f01a615d81f22303e3ae0.zip
      Role:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
          - Arn
      Handler: index.handler
      Layers:
        - Ref: DeploySampleVideoAwsCliLayer2C4BD2C0
      Runtime: python3.7
      Timeout: 900
    DependsOn:
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/Resource
      aws:asset:path: /Users/akodali/pollyblog/polly-blog-cdk/node_modules/aws-cdk-lib/aws-s3-deployment/lib/lambda
      aws:asset:is-bundled: false
      aws:asset:property: Code
  MediaDistributionOrigin1S3Origin173ACFA0:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for PollyBlogCdkStackMediaDistributionOrigin13530716E
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/MediaDistribution/Origin1/S3Origin/Resource
  MediaDistribution4D42B96F:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: PollyBlogCdkStackMediaDistributionOrigin13530716E
          ViewerProtocolPolicy: allow-all
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName:
              Fn::GetAtt:
                - PollyBlogBucket91106725
                - RegionalDomainName
            Id: PollyBlogCdkStackMediaDistributionOrigin13530716E
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: MediaDistributionOrigin1S3Origin173ACFA0
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/MediaDistribution/Resource
  ProcessMediaHandlerServiceRole27ECF250:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/ProcessMediaHandler/ServiceRole/Resource
  ProcessMediaHandler1374F05C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: e89d507e947d298fa3400bc0cc81fb870bb0582b2ac31929c26ffbd287ab8b2d.zip
      Role:
        Fn::GetAtt:
          - ProcessMediaHandlerServiceRole27ECF250
          - Arn
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: PollyBlogBucket91106725
          POLLY_TEXT_FILE: polly_text_file.txt
          MC_ROLE_ARN: ""
          POLLY_LANGUAGE_CODE: hi-IN
          POLLY_VOICE_ID: Aditi
          MC_LANG_SHORT: HIN
          MC_LANG_LONG: Hindi
          TARGET_LANG_CODE: hi
          POLLY_ENGINE: standard
          CDN_URL:
            Fn::GetAtt:
              - MediaDistribution4D42B96F
              - DomainName
          MC_VIDEO_FILENAME: AWS_reInvent_andy_jassy.mp4
      Handler: processMedia.handler
      Runtime: python2.7
    DependsOn:
      - ProcessMediaHandlerServiceRole27ECF250
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/ProcessMediaHandler/Resource
      aws:asset:path: /Users/akodali/pollyblog/polly-blog-cdk/lambda
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/3VRy4oCMRD8lr3H3scs7FlHBEHYRWGvQ0xaaSeTSDpRJMy/b2bi67Knrq70o6rzAZ/w9iLPPFG6nRjaQtoEqVqRqSZxBWkWVYtB1Dt7RSX8OEPq8qCveUlmkrEXXDVJ49G4S4c2QHma3wkhmTEwTIfQCyO7rZaQ8sSVvKD/Rc/krNiQ3RsMzi6iVWFg7iCX3nAvSHaQ1s7gQI/xIbGgXijjot55l9WkOXHwtI3jpG9Pe7JTpZB5qbM4CmNjPTQshob/Kp7HZMsBj7urJG6C5JZhNRpb2pNr8WazMYPFJh9ZGYLpmWtDo2sxXiN/QV62F3Xk4Lo1soteFWNPuHZWU9lrnUY48Ovp/Quq/KEHJpr4mFV2COsS/wB9aHlS6wEAAA==
    Metadata:
      aws:cdk:path: PollyBlogCdkStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

